apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenduser
  labels:
    app: udagram
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram
  template:
    metadata:
      labels:
        app: udagram
    spec:
      containers:
        - name: userapi
          image: nchandlersmith/udagram-api-user:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: udagram-api
            - secretRef:
                name: udagram-secrets
          ports:
            - containerPort: 8080
